apiVersion: v1
baseDomain: DOMAIN
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: CP_REPLICAS
metadata:
  name: lab # Cluster name
    #networking:
    #clusterNetwork:
    #- cidr: 10.128.0.0/14
    #  hostPrefix: 23
    #networkType: OpenShiftDNS 
    #serviceNetwork:
    #- 172.30.0.0/16
platform:
  none: {}
fips: false
