apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels:
      app: redis
spec:
  type: NodePort
  ports:
    - name: redis-statefulset
      protocol: TCP
      port: 6379  
      targetPort: 6379
  selector:
    app: redis
